### ISSUE TITLE
Python exception on MacBook M1 under UTM

### ISSUE THREAD

**Issue by steshaw** [djacu/nixos-dotfiles-work#9]
Hi @djacu,

I'm trying to bootstrap a NixOS VM on macOS under [UTM](https://mac.getutm.app/). I'm using the iso `nixos-minimal-22.05beta140.6848cb6bfc2-aarch64-linux.iso`. I believe that I've followed the instructions correctly but am getting an error when running `bootstrap.main()` in the final step:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/45735/170850141-c6b0275e-375d-410b-a1a0-2c84449a0800.png">

Sorry that I only have a screenshot. Clipboard sharing enabled in the VM.

**Comment by djacu** [comment]
Hey @steshaw 

That is weird. It looks like there is a problem with questionary. I followed the trace back to line where it fails [here](https://github.com/tmbo/questionary/blob/abbc99d8f28cc2061b84ff90c090d4f21b3de6b5/questionary/prompts/common.py#L441). Strange that the line numbers in the stack trace don't match what is shown in the code.

When you're in the python shell can you check the version of questionary? It should be version 1.10.0.
```python
import questionary
print(questionary.__version__)
```

Also, while you're in there, it seems to have failed when trying to ask a questionary checkbox question. After importing questionary, can you try this as well?
```python
response = questionary.checkbox('checkbox test', ['1', '2', '3']).ask()
```

**Comment by steshaw** [comment]
As an experiment, instead of running the following in the live CD environment

```
sudo nix-channel --update
nix-shell
poetry install
nix-build
sudo $(nix-build --no-out-link)/bin/python
```

I just did:

```
sudo nix-channel --update
nix-shell
sudo $(nix-build --no-out-link)/bin/python
```

Then at the Python prompt, `bootstrap.main()` gives the same error as above.
In the same prompt, the`questionary.__version__` is 1.10.0 as you are expecting.

The checkbox test seems to work just fine (modulo my typo 😄):

![image](https://user-images.githubusercontent.com/45735/170905176-f241041b-22b5-4587-a0d7-012bcda6ef87.png)

**Comment by steshaw** [comment]
I also tried following the originial instructions after rebooting the live CD. Briefly, these are all the commands I entered in the live CD environment:

```bash
nix-env -iA nixos.git
git clone https://github.com/djacu/nixos-on-zfs.git
cd ./nixos-on-zfs
sudo nix-channel --list
sudo nix-channel --update
nix-shell
poetry install
nix-build
sudo $(nix-build --no-out-link)/bin/python
```

After `poetry install`, I see:

![image](https://user-images.githubusercontent.com/45735/170906211-82dbc43a-5c34-46cc-88bc-edebbd70edff.png)

After `nix-build`, I see

![image](https://user-images.githubusercontent.com/45735/170906322-14ad1f4e-086b-464b-874a-b2b2d23a1372.png)

After `sudo $(nix-build --no-out-link)/bin/python` followed by issuing the bootstrap in the repl, I see:

![image](https://user-images.githubusercontent.com/45735/170906483-1039540d-a24a-4e15-b436-60e3aa68d646.png)

Which is the same error as above. I then printed the questionary version for good measure:

![image](https://user-images.githubusercontent.com/45735/170906613-819e801d-953e-403e-9365-21ca661b3f1a.png)

Here is line 418 from `common.py` on the Live CD:

![image](https://user-images.githubusercontent.com/45735/170907555-4fbd318c-3ce4-4ebc-bd76-16f42fe69f84.png)

It looks as expected from 1.10.0 https://github.com/tmbo/questionary/blob/1.10.0/questionary/prompts/common.py#L418.

**Comment by steshaw** [comment]
I'm trying to track down the source of the problem and believe it is happening because the list of choices given to the checkbox is empty. This happens during `prepare.add_id_to_block_devices` because there doesn't seem to be a matching path, leading to an empty result:

![image](https://user-images.githubusercontent.com/45735/170939302-0cdfa331-ef08-42d1-b51b-43550106e687.png)

So, the following line is of interest:

https://github.com/djacu/nixos-on-zfs/blob/af11326567073d322eead3d2c04212d05dc3ac6e/pybootstrap/prepare.py#L246

So, the problem is that there is no matching disk in `disks_by_id`. The root cause being that there is only one listed in `/dev/disk/by-id/*`.

![image](https://user-images.githubusercontent.com/45735/170940883-1498eead-21e4-4208-8148-3c2b97e86daa.png)

Any idea why that might be?

**Comment by steshaw** [comment]
It looks like there is a problem with QEMU/libvirt. See https://github.com/systemd/systemd/issues/17670. Apparently it's not a bug. See the [last comment on that issue](https://github.com/systemd/systemd/issues/17670#issuecomment-731261739).

I wonder if there might be an alternative way to pick up the id you need. Here's the output of `udevadm info /dev/vda`:

![image](https://user-images.githubusercontent.com/45735/170967069-49bee187-04c6-4c8b-8e7e-722afd82fc65.png)

There doesn't seem to be a way to provide a dummy serial number for the disk via the UTM UI 😞.

**Comment by djacu** [comment]
Ah good find @steshaw! I never tested this in a virtual environment. 

The whole point of the line you mentioned (below) is to filter the devices found by `lsblk`. Generally, I would find all sorts of extra things like loop back devices, encrypted volumes, and partitions, and I wanted to remove them from the user choices so it was less cluttered.
https://github.com/djacu/nixos-on-zfs/blob/af11326567073d322eead3d2c04212d05dc3ac6e/pybootstrap/prepare.py#L246

I didn't anticipate that a virtual disk would not have a serial number. If you edit `prepare.py` and change line 246 to be
```python
if dev.path == disk.path:
```
that might leave you with a non-empty list.

Edit: If that doesn't work, forcing the conditional to be true, `if True:` _should_ give you something. :sweat_smile:  Let me know how it goes!

**Comment by steshaw** [comment]
I tried `if dev.path == disk.path:` and `if True:` but neither work as `add_id_to_block_devices` attempts to replace the `id` with the `id` from the `new_blk_devs` which only has the CD drive.

Instead, I tried having `add_id_to_block_devices` simply return the `blk_devs` unmodified (in my case, there is only one disk). This seems to get me a lot further along, but then I run into:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/45735/171101370-499d6055-8a2c-426b-b4d9-79a4edd4eec3.png">

I don't have a disk called `/dev/vda-part2` so I figure that not having the `id` replaced in `add_id_to_block_devices` has caused a problem downstream. Fair enough!

I tried setting the `id` to the `path` from `blk_devs`. See https://github.com/steshaw/nixos-on-zfs/blob/utm-compat/pybootstrap/prepare.py#L248. This gave the same error as above with `/dev/vda-part2`.

I only have one disk.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/45735/171102257-a55ef951-29a0-4935-891f-b68c6c28d937.png">

Any ideas?

**Comment by steshaw** [comment]
I decided to try with an x86_64 ISO (rather than arm64).

In this VM, the symbolic links in `/dev/disk/by-id/...` are present but `zpool` still has trouble resolving them even though it resolves to `/dev/sda2`.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/45735/172053630-9d1b71f6-141e-4f96-b427-22e0cc488dd4.png">

Some inspection with `lsblk`:
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/45735/172053935-a64c715b-6c0f-4750-b173-5f7eec55f79e.png">

I used the minimal ISO from the NixOS Download page `nixos-minimal-22.05.518.7a20c208aac-x86_64-linux.iso`.

I recall that this worked for you with QEMU on KVM on your Linux box when we spoke IRL.

**Comment by ghost** [comment]
You should try arm64, however with links in /dev/disk/by-path/*.

I also encountered this problem while testing with virtual machines configured with VirtIO disk controllers.

**Comment by djacu** [comment]
Good news: I got an aarch64 iso running in virt-manager on my system.
Bad news: I ran into the same problem with serial numbers as you did.

I'll modify the prepare.py file similar to what you did to try and get it running. I wonder why this happens on aarch64 systems and not in x86_64. :confused: 

```shell
[nix-shell:~/nixos-on-zfs]$ sudo $(nix-build --no-out-link)/bin/python
Python 3.10.4 (main, Mar 23 2022, 20:25:24) [GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pybootstrap import bootstrap
>>> bootstrap.main()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nixos/nixos-on-zfs/pybootstrap/bootstrap.py", line 4, in main
    config = prepare.prepare()
  File "/home/nixos/nixos-on-zfs/pybootstrap/prepare.py", line 74, in prepare
    disks = get_disks()
  File "/home/nixos/nixos-on-zfs/pybootstrap/prepare.py", line 129, in get_disks
    selection = ask_for_disk_selection(blk_devs)
  File "/home/nixos/nixos-on-zfs/pybootstrap/prepare.py", line 143, in ask_for_disk_selection
    response = questionary.checkbox(
  File "/nix/store/a9bgwq2bvx84qzgk8vfqgch8x443xqj9-python3-3.10.4-env/lib/python3.10/site-packages/questionary/prompts/checkbox.py", line 119, in checkbox
    ic = InquirerControl(
  File "/nix/store/a9bgwq2bvx84qzgk8vfqgch8x443xqj9-python3-3.10.4-env/lib/python3.10/site-packages/questionary/prompts/common.py", line 250, in __init__
    if not self.is_selection_valid():
  File "/nix/store/a9bgwq2bvx84qzgk8vfqgch8x443xqj9-python3-3.10.4-env/lib/python3.10/site-packages/questionary/prompts/common.py", line 421, in is_selection_valid
    return not self.is_selection_disabled() and not self.is_selection_a_separator()
  File "/nix/store/a9bgwq2bvx84qzgk8vfqgch8x443xqj9-python3-3.10.4-env/lib/python3.10/site-packages/questionary/prompts/common.py", line 418, in is_selection_disabled
    return self.choices[self.pointed_at].disabled
AttributeError: 'InquirerControl' object has no attribute 'pointed_at'. Did you mean: 'get_pointed_at'?
>>> import questionary
>>> questionary.__version__
'1.10.0'
>>> 

[nix-shell:~/nixos-on-zfs]$ ls -Fho /dev/disk/by-id/
total 0
lrwxrwxrwx 1 root 9 Jun  6 16:10 scsi-0QEMU_QEMU_CD-ROM_drive-scsi0-0-0-0 -> ../../sr0

nix-shell:~/nixos-on-zfs]$ lsblk -d -o name,kname,path,model,serial,size,type
NAME  KNAME PATH       MODEL       SERIAL              SIZE TYPE
loop0 loop0 /dev/loop0                               739.9M loop
sr0   sr0   /dev/sr0   QEMU CD-ROM drive-scsi0-0-0-0 801.4M rom
vda   vda   /dev/vda                                    20G disk
```

**Comment by ghost** [comment]
It does happen with x86_64 systems, when VirtIO disk controller is used.  We need to use /dev/disk/by-path links.  This is mentioned in the OpenZFS guide.

**Comment by djacu** [comment]
@ne9z did you ever run into issues like this when you were testing aarch64 platforms? The virtual disk, `vda`, does *not* show up in `/dev/disk/by-id/` and does not have a serial number associated with it. This doesn't happen when I use an x86_64 iso. 

This is really annoying because now we cannot use the `/dev/disk/by-id/` symlink to pass to sgdisk but have to use `/dev/` directly. And it creates more problems because if you use `/dev/` with sgdisk to partition, it does *not* add `-partX` to the device name but just adds the number `X`. For example, if we had a device `/dev/disk/by-id/nvme -> /dev/nvme`, and we partition from the `by-id` directory, it will result in a partition `/dev/disk/by-id/nvme-part`. However, if we use sgdisk to partition `/dev/nvme` directly, it will result in a partition `/dev/nvme1`, which messes up the rest of the bootstrapping script because it assumed the partition names would have `-partX` in them.

```shell
[nix-shell:~/nixos-on-zfs]$ lsblk -f
NAME FSTYPE FSVER LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
loop0
     squash 4.0                                                             
sr0  iso966 Jolie nixos-minimal-22.05-aarch64
                        1980-01-01-00-00-00-00                     0   100% /iso
vda                                                                         

[nix-shell:~/nixos-on-zfs]$ lsblk -d -o name,kname,path,model,serial
NAME  KNAME PATH       MODEL       SERIAL
loop0 loop0 /dev/loop0             
sr0   sr0   /dev/sr0   QEMU CD-ROM drive-scsi0-0-0-0
vda   vda   /dev/vda   

[nix-shell:~/nixos-on-zfs]$ ls -n /dev/disk/by-id/
total 0
lrwxrwxrwx 1 0 0 9 Jun  6 16:10 scsi-0QEMU_QEMU_CD-ROM_drive-scsi0-0-0-0 -> ../../sr0
```

**Comment by djacu** [comment]
> It does happen with x86_64 systems, when VirtIO disk controller is used. We need to use /dev/disk/by-path links. This is mentioned in the OpenZFS guide.

I tested this with an x86_64 ISO and it ran just fine - it was like I was running on bare metal. But this is my first time really digging into VMs. So if I create some custom storage instead of using the default VM storage, it might behave properly?

**Comment by ghost** [comment]
I believe that libvirt, the program used to create VMs, defaults to the legacy, fully virtualized QEMU SATA disk controllers when using x86_64 arch.  This disk controller, together with IDE disk controller, which is used for the live CD itself, has serial number assigned by default.


A newer, more performant approach is para-virtualization.  This suite of virtual controllers are called VirtIO controllers.  They do not have serial numbers.


We can not use by-id in this case.  We also can not use direct links inside /dev, therefore we need to use by-path links.  by-path symlinks are guaranteed to exist.

**Comment by steshaw** [comment]
I wonder if we could use partition labels instead of needing to rely on the IDs? I see in the NixOS manual they are [adding labels](https://nixos.org/manual/nixos/stable/#sec-installation-partitioning) with `parted`. I looked at the man page for `sgdisk` but didn't see anything obvious about adding labels.

If we specify the labels, then I think you can use them from `/dev/disk/by-label/*` instead of `by-id`.

![image](https://user-images.githubusercontent.com/45735/172292222-eafd451d-69fc-4c87-a943-ba0252c5d3df.png)

**Comment by ghost** [comment]
According to the manual, there are two partition labels supported by parted: gpt and msdos.  With sgdisk, only gpt is possible.


Anyway, did you try by-path links?  Those are guaranteed to work, at least on VMs.

**Comment by ghost** [comment]
The labels available in by-label are filesystem labels, not partition labels.  Those labels are only available after filesystem creation, i . e. zpool create.  You can not use those before zpool create.


To save some time and frustration, I suggest we test whether by-path works.  Those work pretty well in my experience with VMs. 


They are inconvenient on physical machines though - the order depends on the configuration of the motherboard.

**Comment by steshaw** [comment]
No, I haven't had a look at `by-path` links. I'll take a look. I'm a bit busy, so it may be a little while before I get back to this.

**Comment by ghost** [comment]
The installation script is designed to handle disk symbol links inside /dev/disk/by-*/*-part{1-5}, not direct devices like /dev/{v,s}da{0-5}.  I also encountered this problem during testing.

You should use links inside /dev/disk/by-path/ instead.

**Comment by djacu** [comment]
Sorry for the long delay. Just got back from a long work trip and looking at switching to disks by path.

@ne9z was your testing on an aarch64 architecture? I've had no issues with x86_64 architecture in both a VM and on bare metal. But @steshaw had issues in a VM because they were looking to install it on Mac hardware.

**Comment by djacu** [comment]
I tried switching to `by-path` and ran into problems. There is a branch up if you want to test it.
https://github.com/djacu/nixos-on-zfs/tree/feature/switch-to-disk-by-path

Error message from when I tried to install below. Looks like it has some issue with the EFIs folder.
![Screenshot from 2022-11-01 11-30-45](https://user-images.githubusercontent.com/7043297/199332694-a49d8d23-52ab-4feb-8dff-7d9ca736175a.png)

I'm not certain if this is the cause of the problem but it looks like the by disk path got truncated in the `hardware-configuration-zfs.nix` file. You can see it at the top where it says `fileSystems."/boot/efis/pci-0000:00:06-part1`. File system path is different... Although, that is the correct path under `/boot/efis/`. Hmm not sure
![Screenshot from 2022-11-01 13-14-09](https://user-images.githubusercontent.com/7043297/199332690-d7b90439-5b85-4413-a327-f5013dc42682.png)

And don't worry that the one screenshot has `0000:00:01` and the other has `0000:00:06`. Just screenshots from two different tests. But the errors were exactly the same.

**Comment by djacu** [comment]
As an alternative option, @steshaw and @ne9z, is `/dev/disk/by-uuid` available in your VMs/hardware? That might actually be the best path to go towards because it is reproducible while the other `/dev/disk/by-` paths are not. Would make automation possible in the future.

**Comment by djacu** [comment]
Hmm UUIDs probably are not going to work. Disks don't get a UUID. Only partitions do.
